resources:
  - name: repo
    type: git
    source:
     uri: https://github.com/seiyab/dijkstra-api.git
     branch: master
     interval: 10m

jobs:
  - name: deploy-api
    public: true
    plan:
      - get: repo
        trigger: true
      - task: build
        file: repo/ci/build.yml
      - task: deploy
        file: repo/ci/deploy.yml
